---
output:
  pdf_document:
    template: basic-template.latex
    keep_tex: true
    pandoc_args: ["--top-level-division=chapter", "--filter=c:\\tools\\ruby27\\bin\\pandoc_abnt.bat"]

documentclass: abntex2
fontsize: 12pt
classoption:
  - openright
  - twosided
papersize: a4paper

header-includes: |
  \usepackage{abntex2-relatorio-tecnico}
  \usepackage{lipsum}
  \usepackage{hyperref}
  \usepackage{longtable}

title: Modelo de relatório técnico no formato ABNT escrito no RStudio
author: |
  Leonardo Goes Shibata
  \par
  Mestre em Saúde Pública
date: 2020
institution: Veríssimo & Shibata Consultoria Ltda.
place: São Paulo
#preamble: 
tipotrabalho: Relatório Técnico

capa: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```


# Introdução

\lipsum[1-4]




# Outro capítulo

\lipsum[5-6]

## Primeira seção

\lipsum[7-17]


# Ajustes necessários

## Gráficos

```{r, fig.cap="Título do gráfico"}
ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

Fonte: https://ggplot2.tidyverse.org/



## Tabelas

```{r}
knitr::kable(head(iris), format = "pandoc")
```

: Exemplo de tabela \label{exemplo-tabela}

Fonte: documentação kable.  
Nota: Exemplo de nota.
